coverage:
  range: 70..100
  round: down
  precision: 1

codecov:
  # You will need to get a new token for your repo or at least remove this one, as
  # they are tied to individual repositories
  token: 81792ea5-0d84-4533-b318-b28a8e02f047
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true

comment:
  after_n_builds: 1

github_checks:
  annotations: false
