services:
  pudl-archiver:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
  # fsspec archives use GCS for production backend
  pudl-archiver-fsspec:
    extends:
      service: pudl-archiver
    volumes:
      - ~/.config/gcloud:/home/appuser/.config/gcloud:ro
  pudl-archiver-pytest:
    extends:
      service: pudl-archiver
    entrypoint: ["pixi", "run", "python", "-m", "pytest"]
