---
name: pudl-archiver
channels:
  - conda-forge
  - defaults
dependencies:
  # Used to set up the environment
  - pip>=21,<23
  - python>=3.10,<3.11
  - setuptools<66
  - pip:
      - --editable ./[dev,docs,tests]
