---
name: pudl-cataloger
channels:
  - conda-forge
  - defaults
dependencies:
  # Used to set up the environment
  - pip>=21,<24
  - python>=3.11,<3.12
  - setuptools>=66
  - pip:
      - --editable ./[dev,docs,tests]
