---
name: pudl-scrapers
channels:
  - conda-forge
  - defaults
dependencies:
  # Used to set up the environment
  - pip>=21,<23
  - python>=3.10,<3.11
  - setuptools<64
  - pip:
      - --editable ./[dev,docs,tests]
