---
name: publish-fsspec-archive

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Github action run ID, which is the number at the end of the URL when looking at a run
        required: true
        type: string
      command:
        description: Switch between the retry-run and publish-run command
        required: true
        type: choice
        default: "publish-run"
        options:
          - publish-run
          - retry-run

jobs:
  publish-run:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v7

      - name: Set default GCP credentials
        id: gcloud-auth
        continue-on-error: true
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: "projects/345950277072/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions-provider"
          service_account: "pudl-archiver-gha@catalyst-cooperative-pudl.iam.gserviceaccount.com"

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          cache: true

      - name: Log the pixi environment
        run: |
          pixi info
          pixi list

      - name: Additional Playwright setup
        run: |
          pixi run playwright install --with-deps webkit
          pixi run playwright install --with-deps chromium

      - name: Download run summary
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ inputs.run_id }}
          pattern: run-summaries-*
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get dataset from run summary filename
        id: dataset_name
        run: |
          file=$(find summaries -name '*_run_summary.json')
          echo "dataset=$(basename "$file" _run_summary.json)" >> "$GITHUB_OUTPUT"

      - name: Attempt to publish deposition for ${{ steps.dataset_name.outputs.dataset }}
        # set -o pipefail passes on any failure codes to the next step,
        # enabling us to see whether or not the pudl_archiver run failed.
        run: |
          set -o pipefail
          pixi run pudl_archiver \
            ${{ inputs.command }} \
            ${{ steps.dataset_name.outputs.dataset }}_run_summary.json 2>&1 | tee ${{ steps.dataset_name.outputs.dataset }}_log.txt

      - name: Upload run summaries
        if: always()
        id: upload_summaries
        uses: actions/upload-artifact@v7
        with:
          name: run-summaries-${{ steps.dataset_name.outputs.dataset }}
          path: ${{ steps.dataset_name.outputs.dataset }}_run_summary.json

      - name: Save failed runs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: error-log-${{ steps.dataset_name.outputs.dataset }}
          path: ${{ steps.dataset_name.outputs.dataset }}_log.txt
