---
name: run-archiver-cambium

on:
  workflow_dispatch:

jobs:
  archive-run:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest-4core
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
